### ISSUE TITLE
Where to find TSI_API_KEY?

### ISSUE THREAD

**Issue by Jing-yilin** [telekom/create-tsi#5]
I got no idea what is actually TSI_API_KEY.

**Comment by dinakar17** [comment]
Same here

**Comment by marcusschiesser** [comment]
I got mine from @andrej-schreiner, but that's a good point: there should be a sign up link in the readme

**Comment by josephgoksu** [comment]
@andrej-schreiner Could you help us find the TS_API_KEY? Is it something that we can generate from the cloud provider or?

**Comment by andrej-schreiner** [comment]
> @andrej-schreiner Could you help us find the TS_API_KEY? Is it something that we can generate from the cloud provider or?

@josephgoksu @Jing-yilin I will get back on that on Monday (we are working on our portal to generate demo keys, at the moment only enterprise customers have keys)

**Comment by igorschlum** [comment]
Would be pleased to have one too.

**Comment by andrej-schreiner** [comment]
> Thanks @andrej-schreiner Filled the form and submitted. How does it work? Do we get the key in eMail or ...? How long would it take? (i.e. is it automated or manual task?)

Should not take longer than 24h and you get a key
